// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpenses = `-- name: CountExpenses :one
SELECT COUNT(*) FROM expenses e
WHERE
    ($1::date IS NULL OR e.date >= $1::date)
    AND ($2::date IS NULL OR e.date <= $2::date)
    AND ($3::uuid IS NULL OR e.category_id = $3::uuid)
    AND ($4::decimal IS NULL OR e.amount >= $4::decimal)
    AND ($5::decimal IS NULL OR e.amount <= $5::decimal)
    AND ($6::text IS NULL OR e.note ILIKE '%' || $6::text || '%')
`

type CountExpensesParams struct {
	FromDate   pgtype.Date    `json:"from_date"`
	ToDate     pgtype.Date    `json:"to_date"`
	CategoryID pgtype.UUID    `json:"category_id"`
	MinAmount  pgtype.Numeric `json:"min_amount"`
	MaxAmount  pgtype.Numeric `json:"max_amount"`
	Search     pgtype.Text    `json:"search"`
}

func (q *Queries) CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenses,
		arg.FromDate,
		arg.ToDate,
		arg.CategoryID,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (amount, currency, note, category_id, date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, amount, currency, note, category_id, date, created_at, updated_at
`

type CreateExpenseParams struct {
	Amount     pgtype.Numeric `json:"amount"`
	Currency   string         `json:"currency"`
	Note       pgtype.Text    `json:"note"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Date       pgtype.Date    `json:"date"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.CategoryID,
		arg.Date,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CategoryID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT e.id, e.amount, e.currency, e.note, e.category_id, e.date, e.created_at, e.updated_at, c.name as category_name, c.icon as category_icon, c.color as category_color
FROM expenses e
JOIN categories c ON e.category_id = c.id
WHERE e.id = $1
`

type GetExpenseRow struct {
	ID            pgtype.UUID        `json:"id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	Note          pgtype.Text        `json:"note"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Date          pgtype.Date        `json:"date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  string             `json:"category_name"`
	CategoryIcon  pgtype.Text        `json:"category_icon"`
	CategoryColor pgtype.Text        `json:"category_color"`
}

func (q *Queries) GetExpense(ctx context.Context, id pgtype.UUID) (GetExpenseRow, error) {
	row := q.db.QueryRow(ctx, getExpense, id)
	var i GetExpenseRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CategoryID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.CategoryColor,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.amount, e.currency, e.note, e.category_id, e.date, e.created_at, e.updated_at, c.name as category_name, c.icon as category_icon, c.color as category_color
FROM expenses e
JOIN categories c ON e.category_id = c.id
WHERE
    ($1::date IS NULL OR e.date >= $1::date)
    AND ($2::date IS NULL OR e.date <= $2::date)
    AND ($3::uuid IS NULL OR e.category_id = $3::uuid)
    AND ($4::decimal IS NULL OR e.amount >= $4::decimal)
    AND ($5::decimal IS NULL OR e.amount <= $5::decimal)
    AND ($6::text IS NULL OR e.note ILIKE '%' || $6::text || '%')
ORDER BY e.date DESC, e.created_at DESC
LIMIT $8::int
OFFSET $7::int
`

type ListExpensesParams struct {
	FromDate    pgtype.Date    `json:"from_date"`
	ToDate      pgtype.Date    `json:"to_date"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	MinAmount   pgtype.Numeric `json:"min_amount"`
	MaxAmount   pgtype.Numeric `json:"max_amount"`
	Search      pgtype.Text    `json:"search"`
	QueryOffset int32          `json:"query_offset"`
	QueryLimit  int32          `json:"query_limit"`
}

type ListExpensesRow struct {
	ID            pgtype.UUID        `json:"id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	Note          pgtype.Text        `json:"note"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Date          pgtype.Date        `json:"date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  string             `json:"category_name"`
	CategoryIcon  pgtype.Text        `json:"category_icon"`
	CategoryColor pgtype.Text        `json:"category_color"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.FromDate,
		arg.ToDate,
		arg.CategoryID,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.Note,
			&i.CategoryID,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET amount = $1, currency = $2, note = $3, category_id = $4, date = $5, updated_at = NOW()
WHERE id = $6
RETURNING id, amount, currency, note, category_id, date, created_at, updated_at
`

type UpdateExpenseParams struct {
	Amount     pgtype.Numeric `json:"amount"`
	Currency   string         `json:"currency"`
	Note       pgtype.Text    `json:"note"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Date       pgtype.Date    `json:"date"`
	ID         pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.CategoryID,
		arg.Date,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CategoryID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
