// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID         pgtype.UUID        `json:"id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Currency   string             `json:"currency"`
	Period     string             `json:"period"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Icon      pgtype.Text        `json:"icon"`
	Color     pgtype.Text        `json:"color"`
	IsDefault pgtype.Bool        `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type Expense struct {
	ID         pgtype.UUID        `json:"id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Currency   string             `json:"currency"`
	Note       pgtype.Text        `json:"note"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Date       pgtype.Date        `json:"date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
}

type RecurringExpense struct {
	ID         pgtype.UUID        `json:"id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Currency   string             `json:"currency"`
	Note       pgtype.Text        `json:"note"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Frequency  string             `json:"frequency"`
	NextDate   pgtype.Date        `json:"next_date"`
	Active     pgtype.Bool        `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
