// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurring = `-- name: CreateRecurring :one
INSERT INTO recurring_expenses (amount, currency, note, category_id, frequency, next_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, amount, currency, note, category_id, frequency, next_date, active, created_at, updated_at
`

type CreateRecurringParams struct {
	Amount     pgtype.Numeric `json:"amount"`
	Currency   string         `json:"currency"`
	Note       pgtype.Text    `json:"note"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Frequency  string         `json:"frequency"`
	NextDate   pgtype.Date    `json:"next_date"`
}

func (q *Queries) CreateRecurring(ctx context.Context, arg CreateRecurringParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurring,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.CategoryID,
		arg.Frequency,
		arg.NextDate,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CategoryID,
		&i.Frequency,
		&i.NextDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurring = `-- name: DeleteRecurring :exec
DELETE FROM recurring_expenses WHERE id = $1
`

func (q *Queries) DeleteRecurring(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecurring, id)
	return err
}

const getDueRecurring = `-- name: GetDueRecurring :many
SELECT id, amount, currency, note, category_id, frequency, next_date, active, created_at, updated_at FROM recurring_expenses
WHERE active = true AND next_date <= $1
`

func (q *Queries) GetDueRecurring(ctx context.Context, nextDate pgtype.Date) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, getDueRecurring, nextDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.Note,
			&i.CategoryID,
			&i.Frequency,
			&i.NextDate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurring = `-- name: ListRecurring :many
SELECT r.id, r.amount, r.currency, r.note, r.category_id, r.frequency, r.next_date, r.active, r.created_at, r.updated_at, c.name as category_name, c.icon as category_icon, c.color as category_color
FROM recurring_expenses r
JOIN categories c ON r.category_id = c.id
ORDER BY r.next_date
`

type ListRecurringRow struct {
	ID            pgtype.UUID        `json:"id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	Note          pgtype.Text        `json:"note"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Frequency     string             `json:"frequency"`
	NextDate      pgtype.Date        `json:"next_date"`
	Active        pgtype.Bool        `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  string             `json:"category_name"`
	CategoryIcon  pgtype.Text        `json:"category_icon"`
	CategoryColor pgtype.Text        `json:"category_color"`
}

func (q *Queries) ListRecurring(ctx context.Context) ([]ListRecurringRow, error) {
	rows, err := q.db.Query(ctx, listRecurring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringRow{}
	for rows.Next() {
		var i ListRecurringRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.Note,
			&i.CategoryID,
			&i.Frequency,
			&i.NextDate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurring = `-- name: UpdateRecurring :one
UPDATE recurring_expenses
SET amount = $1, currency = $2, note = $3, category_id = $4, frequency = $5, next_date = $6, active = $7, updated_at = NOW()
WHERE id = $8
RETURNING id, amount, currency, note, category_id, frequency, next_date, active, created_at, updated_at
`

type UpdateRecurringParams struct {
	Amount     pgtype.Numeric `json:"amount"`
	Currency   string         `json:"currency"`
	Note       pgtype.Text    `json:"note"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Frequency  string         `json:"frequency"`
	NextDate   pgtype.Date    `json:"next_date"`
	Active     pgtype.Bool    `json:"active"`
	ID         pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurring,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.CategoryID,
		arg.Frequency,
		arg.NextDate,
		arg.Active,
		arg.ID,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CategoryID,
		&i.Frequency,
		&i.NextDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
