// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summary.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategorySummary = `-- name: GetCategorySummary :many
SELECT
    c.id as category_id,
    c.name as category_name,
    c.icon as category_icon,
    c.color as category_color,
    COALESCE(SUM(e.amount), 0)::decimal as total_spent,
    COUNT(e.id) as expense_count
FROM categories c
LEFT JOIN expenses e ON c.id = e.category_id AND e.date >= $2 AND e.date <= $3 AND e.user_id = $1
WHERE (c.is_default = true OR c.user_id = $1)
GROUP BY c.id, c.name, c.icon, c.color
HAVING COUNT(e.id) > 0
ORDER BY total_spent DESC
`

type GetCategorySummaryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetCategorySummaryRow struct {
	CategoryID    pgtype.UUID    `json:"category_id"`
	CategoryName  string         `json:"category_name"`
	CategoryIcon  pgtype.Text    `json:"category_icon"`
	CategoryColor pgtype.Text    `json:"category_color"`
	TotalSpent    pgtype.Numeric `json:"total_spent"`
	ExpenseCount  int64          `json:"expense_count"`
}

func (q *Queries) GetCategorySummary(ctx context.Context, arg GetCategorySummaryParams) ([]GetCategorySummaryRow, error) {
	rows, err := q.db.Query(ctx, getCategorySummary, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategorySummaryRow{}
	for rows.Next() {
		var i GetCategorySummaryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.TotalSpent,
			&i.ExpenseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpending = `-- name: GetDailySpending :many
SELECT
    e.date,
    COALESCE(SUM(e.amount), 0)::decimal as total_spent
FROM expenses e
WHERE e.user_id = $1 AND e.date >= $2 AND e.date <= $3
GROUP BY e.date
ORDER BY e.date
`

type GetDailySpendingParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetDailySpendingRow struct {
	Date       pgtype.Date    `json:"date"`
	TotalSpent pgtype.Numeric `json:"total_spent"`
}

func (q *Queries) GetDailySpending(ctx context.Context, arg GetDailySpendingParams) ([]GetDailySpendingRow, error) {
	rows, err := q.db.Query(ctx, getDailySpending, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySpendingRow{}
	for rows.Next() {
		var i GetDailySpendingRow
		if err := rows.Scan(&i.Date, &i.TotalSpent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :one
SELECT
    COALESCE(SUM(amount), 0)::decimal as total_spent,
    COALESCE(AVG(amount), 0)::decimal as avg_expense,
    COUNT(*) as total_count
FROM expenses
WHERE user_id = $1 AND date >= $2 AND date <= $3
`

type GetMonthlySummaryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetMonthlySummaryRow struct {
	TotalSpent pgtype.Numeric `json:"total_spent"`
	AvgExpense pgtype.Numeric `json:"avg_expense"`
	TotalCount int64          `json:"total_count"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) (GetMonthlySummaryRow, error) {
	row := q.db.QueryRow(ctx, getMonthlySummary, arg.UserID, arg.Date, arg.Date_2)
	var i GetMonthlySummaryRow
	err := row.Scan(&i.TotalSpent, &i.AvgExpense, &i.TotalCount)
	return i, err
}
